export interface SearchIndexEntry {
  /** 路由路径，如 /sources */
  path: string;
  /** 页面显示标题 */
  title: string;
  /** 章节锚点，如 #s7；无锚点为空字符串 */
  anchor: string;
  /** 章节标题（用于结果展示） */
  section: string;
  /** 该章节的可搜索文本（标题 + 正文关键词，已去除 HTML 标签与模板语法） */
  keywords: string;
}

/**
 * 文档站点的全量搜索索引。
 * 每条记录对应某个页面中一个章节（h2/h3）。
 * 章节内的正文已被抽取为纯文本关键词串，便于做包含匹配。
 */
export const SEARCH_INDEX: SearchIndexEntry[] = [
  {
    path: '/home',
    title: '首页',
    anchor: '',
    section: '这是什么？',
    keywords: '电视直播 mytv-android Android TV 电视直播应用 Kotlin Jetpack Compose 订阅源 m3u Xtream Stalker 本地文件 EPG 节目单 XML DIYP LOVETV WebView 播放器 多屏同播 云同步 Gist WebDAV Gitee ASR 实时字幕 翻译',
  },
  {
    path: '/home',
    title: '首页',
    anchor: '',
    section: '主要特性速览',
    keywords: '多种订阅源 m3u txt Xtream Codes Stalker Portal webView:// video:// javascript:// 混合源 CCTV CETV 省级卫视 央视频 官网 EPG 回看 远程配置面板 10591 多屏同播 云同步 GitHub Gist Gitee WebDAV 网络链接 本地文件 ASR 实时字幕 翻译 加密分组 隐藏规则 画中画 开机自启 启动页',
  },
  {
    path: '/getting-started',
    title: '快速上手',
    anchor: '',
    section: '安装',
    keywords: '安装 APK 下载 Android 6.0 API 23 横屏 安装未知应用 权限',
  },
  {
    path: '/getting-started',
    title: '快速上手',
    anchor: '',
    section: '首次启动',
    keywords: '首次启动 演示源 订阅源 引导 设置',
  },
  {
    path: '/getting-started',
    title: '快速上手',
    anchor: '',
    section: '配置订阅源',
    keywords: '配置订阅源 添加订阅 二维码 面板 推送 m3u URL',
  },
  {
    path: '/controls',
    title: '遥控器与触屏',
    anchor: '',
    section: '遥控器按键',
    keywords: '遥控器按键 OK 方向键 菜单键 返回键 主页键 数字键 快捷键 映射 KeyDownAction ChangeCurrentChannelToPrev ChangeCurrentChannelToNext ChangeCurrentChannelLineIdxToPrev ChangeCurrentChannelLineIdxToNext ToChannelScreen ToQuickOpScreen ToIptvSourceScreen ToVideoPlayerControllerScreen ToEpgScreen ToChannelLineScreen',
  },
  {
    path: '/controls',
    title: '遥控器与触屏',
    anchor: '',
    section: '触屏手势',
    keywords: '触屏 手势 单击 双击 长按 滑动 缩放 上键/上滑 下键/下滑 左键/左滑 右键/右滑 选择键 长按选择键 长按上键 长按下键 长按左键 长按右键',
  },
  {
    path: '/controls',
    title: '遥控器与触屏',
    anchor: '',
    section: '数字换台',
    keywords: '数字换台 数字键 频道号 输入 跳转 iptvChannelNoSelectEnable 数字选台 通过数字键选择频道',
  },
  {
    path: '/controls',
    title: '遥控器与触屏',
    anchor: '',
    section: '防误触',
    keywords: '防误触 按键间隔 连按 屏蔽 无操作 NoAction',
  },
  {
    path: '/controls',
    title: '遥控器与触屏',
    anchor: '',
    section: 'TV 应用内设置项',
    keywords: '控制设置 频道切换跨分组 iptvChannelChangeCrossGroup 频道列表首尾循环 iptvChannelChangeListLoop 数字选台 iptvChannelNoSelectEnable 长按OK 按键行为 跨组切换 keyDownEventUp keyDownEventDown keyDownEventLeft keyDownEventRight keyDownEventSelect keyDownEventLongUp keyDownEventLongDown keyDownEventLongLeft keyDownEventLongRight keyDownEventLongSelect 前一频道 后一频道 前一线路 后一线路 快进 快退 管理订阅源 频道列表 快捷设置 节目单 线路列表 播放控制 无操作 13种行为',
  },
  {
    path: '/live-screen',
    title: '直播主界面',
    anchor: '',
    section: 'Dashboard 组成',
    keywords: 'Dashboard Header 订阅源名 时钟 MM/dd EEE HH:mm:ss 导航模块 收藏区 最近观看 模块网格 3列 直播 全部频道 收藏 节目单 搜索 设置 多屏同播 推送 关于',
  },
  {
    path: '/live-screen',
    title: '直播主界面',
    anchor: '',
    section: '直播播放器界面',
    keywords: '播放器界面 频道信息条 线路名 EPG 节目 进度条 台标 回放标志 PlayerActivity iptvChannelChangeShowInfoPanel 换台时显示频道信息',
  },
  {
    path: '/live-screen',
    title: '直播主界面',
    anchor: '',
    section: 'TV 应用内设置项（设置 → 界面）',
    keywords: '界面设置 节目进度 uiShowEpgProgrammeProgress 常驻节目进度 uiShowEpgProgrammePermanentProgress 台标显示 uiShowChannelLogo 显示回放标志 uiShowReplayBadge 左上角 频道预览 uiShowChannelPreview 频道预览并行数 channelPreviewParallelCount 1-10 列表项动画 uiListAnimation 列表懒渲染 uiLazyRender 懒渲染每批并行数 uiLazyRenderParallelCount 懒渲染间隔 uiLazyRenderInterval -1 50 100 200 300 500 1000 2000 ms 经典选台界面 uiUseClassicPanelScreen 显示订阅源列表 uiClassicShowSourceList 显示频道信息 uiClassicShowChannelInfo 单独显示频道号 uiClassicShowChannelNo 显示全部频道 uiClassicShowAllChannels 换台时显示频道信息 iptvChannelChangeShowInfoPanel 时间显示 uiTimeShowMode 隐藏 常显 整点 半点 30秒 超时自动关闭界面 uiScreenAutoCloseDelay 5 10 15 20 25 30秒 不关闭 界面整体缩放比例 uiDensityScaleRatio 自适应 0.5-2.0 界面字体缩放比例 uiFontScaleRatio 字幕设置 焦点优化 uiFocusOptimize 触摸设备闪退 启用收藏 iptvChannelFavoriteEnable 启用最近观看 iptvChannelHistoryEnable 15条历史',
  },
  {
    path: '/live-screen',
    title: '直播主界面',
    anchor: '',
    section: '主题',
    keywords: '主题 颜色模式 配色方案 主题包 恢复默认 背景色 贴图 贴图透明度 自定义主题',
  },
  {
    path: '/live-screen',
    title: '直播主界面',
    anchor: '',
    section: '画中画与启动页',
    keywords: '画中画 启动页面 首页 直播 节目单 全部频道 收藏 搜索 多屏同播',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '频道列表',
    keywords: '频道列表 分组条形 频道网格 经典选台界面 uiUseClassicPanelScreen 现代面板 三段式 显示订阅源列表 uiClassicShowSourceList 向左查看订阅源 显示频道信息 uiClassicShowChannelInfo 单独显示频道号 uiClassicShowChannelNo 频道名首字 显示全部频道 uiClassicShowAllChannels /ui remoteConfig',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '跨组切换与循环',
    keywords: '频道切换跨分组 iptvChannelChangeCrossGroup 上下键 所有频道 当前分组 频道列表首尾循环 iptvChannelChangeListLoop 首尾循环 /control',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '加密分组',
    keywords: '加密分组 iptvChannelGroupEncrypted 支持加密频道组 密码 _数字 分组名 搜索隐藏 全部频道隐藏 选台界面 成人',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '收藏夹',
    keywords: '收藏 收藏夹 长按OK 收藏分组 清空 启用收藏 iptvChannelFavoriteEnable 是否显示当前订阅源频道收藏列表 备份 云同步',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '隐藏频道与分组',
    keywords: '隐藏 分类隐藏 iptvChannelGroupHiddenList Set 共N个分组 已隐藏M个分组 隐藏频道规则 iptvChannelHiddenList 正则 .*测试.* 频道名 chips',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '搜索',
    keywords: '搜索 关键词 拼音首字母 contains 防抖 加密分组 隐藏规则 屏幕键盘',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '多屏同播（MultiView）',
    keywords: '多屏同播 MultiView 9路 同屏 方案 布局 放大 缩小 暂停 静音 切换线路 回看 移动屏幕',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '频道别名',
    keywords: '频道别名 iptvChannelAlias remoteConfig 只读 __suffix 标准名 别名数组 共N个频道M个别名 相似频道合并 iptvSimilarChannelMerge 相同频道别名合并',
  },
  {
    path: '/channels',
    title: '频道、收藏与搜索',
    anchor: '',
    section: '频道图标',
    keywords: '频道图标 tvg-logo 频道图标提供 iptvChannelLogoProvider gitee myTVlogo URL模板 变量 name lowercase uppercase 10天周期 缓存过期 频道图标覆盖 iptvChannelLogoOverride 覆盖订阅源',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: '订阅源类型',
    keywords: '订阅源类型 sourceType 网络 m3u txt 本地文件 Xtream Codes Stalker Portal get.php handshake 必填字段 gz GZIP',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: '添加订阅源',
    keywords: '添加订阅源 二维码 面板 remote xtream stalker file content 粘贴 m3u 内容 深链 mytv://add nanotv:// play.aptv.app POST /api/iptv-source/push',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: 'm3u 支持的扩展字段',
    keywords: 'EXTM3U EXTINF tvg-id tvg-name tvg-logo tvg-chno group-title http-user-agent http-referrer http-origin http-cookie host catchup catchup-source x-tvg-url url-tvg KODIPROP EXTVLCOPT DRM stream_headers',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: '回看类型',
    keywords: '回看类型 catchup default append timeshift shift flussonic xtream codes disabled 内部值',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: 'URL 前缀（混合源协议）',
    keywords: 'URL前缀 webview:// video:// javascript:// hybridType 混合源协议 QuickJS',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: 'javascript:// 源',
    keywords: 'javascript:// QuickJS 动态拼接 一次额外请求 解密 播放地址 开发者模式 ku9 调试',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: '混合源（自动添加网页源）',
    keywords: '混合源 自动添加网页源 央视网 cctv.com 央视频 yangshipin.cn 官网 brtn jstv kankanews cztv hebtv gdtv gxtv hljtv hnntv hntv fjtv gzstv jxntv ahtv iqilu 兜底 tag 内置源 host 判定',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: 'TV 应用内设置项（设置 → 订阅源）',
    keywords: '订阅源设置 自定义订阅源 WebView测试源 类型徽标 转换JS徽标 刷新全部 订阅源缓存时间 不缓存 永久 1小时 15天 humanizeMs 分类隐藏 隐藏频道规则 正则 .*测试.* 支持加密频道组 _数字 密码 频道别名 channel_name_alias.json __suffix 相似频道合并 频道图标提供 gitee myTVlogo name lowercase uppercase 10天周期 频道图标覆盖 PLTV转TVOD rtsp pltv tvod playseek 自动添加网页源 禁用 订阅源优先 IPTV_FIRST 网页源优先 HYBRID_FIRST 网页源央视频Cookie yangshipin.cn 前50字符',
  },
  {
    path: '/sources',
    title: '订阅源（IPTV）',
    anchor: '',
    section: '10591 面板（/sources）的全部可配置项',
    keywords: '面板订阅源 排序 上移下移 设为当前 编辑对话框 类型 remote file xtream stalker 链接 文件路径 文件内容 用户名密码 输出类型 m3u_plus MAC地址 全局UA httpUserAgent HTTP代理 httpProxy 代理优先级 播放器代理规则 转换JS transformJs function main 订阅源缓存时间 频道隐藏分组 频道隐藏列表 频道别名 channel_name_alias.json 清空缓存 相似频道合并 频道图标提供 频道图标覆盖 PLTV转TVOD 自动添加网页源 网页源央视频Cookie /api/iptv-source/push /api/channel-alias /api/file/content',
  },
  {
    path: '/epg',
    title: 'EPG 节目单',
    anchor: '',
    section: 'EPG 来源类型',
    keywords: 'EPG来源 XML XMLTV XML_GZ gzip DIYP LOVETV CHUNKED_XML 超级直播 EpgSourceType fromUrl 自动探测 channel={name} ch={name} diyp:// lovetv://',
  },
  {
    path: '/epg',
    title: 'EPG 节目单',
    anchor: '',
    section: '添加 EPG 源',
    keywords: '添加EPG源 二维码 面板 自定义节目单 拖拽排序 EpgSource name url 空字符串跳过 刷新全部 设为当前 删除 清除缓存 ui_settings_epg_source_item_info 频道数 节目数 缓存大小 更新时间',
  },
  {
    path: '/epg',
    title: 'EPG 节目单',
    anchor: '',
    section: 'TV 应用内设置项（设置 → 节目单）',
    keywords: '节目单设置 节目单启用 ui_epg_enable 跟随订阅源 ui_epg_source_follow_iptv 加载全部节目单 ui_epg_source_load_all 经典选台界面节目单常显 ui_epg_always_show_in_classic_channel_screen 自定义节目单 ui_epg_source_custom 刷新时间阈值 ui_epg_refresh_time_threshold Configs SpState epgEnable epgSourceFollowIptv epgSourceLoadAll alwaysShowEPGInClassicChannelScreen EPG_REFRESH_TIME_THRESHOLD=2 启动时刷新 epg_loaded_on_Startup 6列网格 -1 0..12',
  },
  {
    path: '/epg',
    title: 'EPG 节目单',
    anchor: '',
    section: '10591 面板（/epg）的全部可配置项',
    keywords: '面板EPG 节目单启用 EPG.ENABLE 经典选台界面节目单常显 EPG.ALWAYS_SHOW_IN_CLASSIC 跟随订阅源 EPG.FOLLOW_SOURCE 加载全部节目单 EPG.LOAD_ALL 自定义节目单 EPG.CUSTOM_EPG app-epg-manager cdkDropList 拖拽手柄 刷新时间阈值 EPG.REFRESH_THRESHOLD app-epg-threshold-dialog 每次启动 THRESHOLD_ALWAYS 00:00 06:00 12:00 18:00 自定义 CUSTOM min=0 step=0.5 小数小时 HH:MM EPG源编辑 名称 HOME.NAME 链接 HOME.LINK 必填 matInput',
  },
  {
    path: '/epg',
    title: 'EPG 节目单',
    anchor: '',
    section: 'EPG 与频道的匹配',
    keywords: 'EPG匹配 EpgList.match tvg-id tvg-name Channel.epgID Channel.epgName standardName displayName 频道别名 CHANNEL_ALIAS 归并 逻辑频道 epgSourceFollowIptv 大小写不敏感 索引查找',
  },
  {
    path: '/epg',
    title: 'EPG 节目单',
    anchor: '',
    section: 'EPG 显示位置',
    keywords: 'EPG显示 频道信息条 换台 下一个节目 进度条 EPG指南页 二维表格 全局EPG切换键 EpgGuideActivity 长按左方向键',
  },
  {
    path: '/epg',
    title: 'EPG 节目单',
    anchor: '',
    section: '回看',
    keywords: '回看 catchup catchup-source M3uIptvParser default append timeshift shift flussonic xtream codes disabled 全局EXTM3U EXTINF LIVE_SEEKTO_MAX_REWIND_HOURS 48小时 已播出节目',
  },
  {
    path: '/webview-player',
    title: 'WebView 播放器',
    anchor: '',
    section: '什么是 WebView 播放器',
    keywords: 'WebView播放器 webview:// 防盗链 登录 网页 video 提取 原生播放器',
  },
  {
    path: '/webview-player',
    title: 'WebView 播放器',
    anchor: '',
    section: '三种 URL 前缀',
    keywords: 'URL前缀 webview:// video:// javascript:// 提取 纯视频流',
  },
  {
    path: '/webview-player',
    title: 'WebView 播放器',
    anchor: '',
    section: '使用方法',
    keywords: '使用方法 webview:// 播放器 自动启动 全屏 加载超时 失败 切换线路',
  },
  {
    path: '/webview-player',
    title: 'WebView 播放器',
    anchor: '',
    section: 'TV 应用内设置项（设置 → WebView 播放器）',
    keywords: 'WebView设置 WebView内核 系统WebView TBS X5 腾讯X5 armv7 arm64 在线下载 回退 替换系统WebView com.google.android.webview 重启生效 WebView加载超时',
  },
  {
    path: '/webview-player',
    title: 'WebView 播放器',
    anchor: '',
    section: '10591 面板（/webview）的全部可配置项',
    keywords: '面板WebView WebView内核 SYSTEM X5 替换系统WebView 加载超时 毫秒',
  },
  {
    path: '/webview-player',
    title: 'WebView 播放器',
    anchor: '',
    section: '央视频 Cookie',
    keywords: '央视频 Cookie yangshipin.cn 付费频道 登录 注入',
  },
  {
    path: '/webview-player',
    title: 'WebView 播放器',
    anchor: '',
    section: '常见问题',
    keywords: 'WebView常见问题 全屏 提取不到流 DRM 自定义播放器 央视频黑屏 X5下载失败',
  },
  {
    path: '/remote-panel',
    title: '远程配置面板',
    anchor: '',
    section: '怎么打开',
    keywords: '打开面板 局域网 10591 端口 二维码 设备IP lang 语言',
  },
  {
    path: '/remote-panel',
    title: '远程配置面板',
    anchor: '',
    section: '面板页面一览',
    keywords: '面板路由 /general /sources /epg /ui /theme /control /player /webview /network /update /sync /debug /log 首页',
  },
  {
    path: '/remote-panel',
    title: '远程配置面板',
    anchor: '',
    section: '首页能快速做什么',
    keywords: '面板首页 推送订阅源 content 粘贴 网页源央视频Cookie 频道图标提供 频道别名 推送节目单 播放器全局设置 云同步 安装APK 关于应用',
  },
  {
    path: '/remote-panel',
    title: '远程配置面板',
    anchor: '',
    section: 'TV 设置页 vs 10591 面板',
    keywords: 'TV面板对比 只能面板 排序 transformJs 单源UA 代理 EPG拖拽 正则解码配置 代理规则 ASR凭据 云同步账号 导入导出 推APK logcat',
  },
  {
    path: '/remote-panel',
    title: '远程配置面板',
    anchor: '',
    section: 'HTTP API（高级）',
    keywords: 'HTTP API /api/info /api/about /api/logs /api/logcat /api/iptv-source/push /api/epg-source/push /api/channel-alias /api/configs /api/file/content /api/file/content-with-dir /api/cloud-sync/data /api/upload/apk /api/local.m3u8 /ku9/js',
  },
  {
    path: '/remote-panel',
    title: '远程配置面板',
    anchor: '',
    section: '典型用法',
    keywords: 'curl 典型用法 推订阅源 推EPG 改全局UA 示例命令',
  },
  {
    path: '/remote-panel',
    title: '远程配置面板',
    anchor: '',
    section: '安全说明',
    keywords: '安全 10591 无鉴权 CORS 局域网 端口映射 公网',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '视频播放器内核',
    keywords: '播放器内核 Media3 ExoPlayer IjkPlayer FFmpeg VLC 在线下发 组件管理 下载 删除 未下载 下载中 校验中 解压中 已安装 下载失败 label 枚举 默认MEDIA3 RTSP单播',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '解码与渲染',
    keywords: '渲染方式 SurfaceView TextureView 动画 截图 默认SurfaceView 强制软解 MediaCodec FFmpeg 设备软解 扩展软解 花屏 硬解 CPU 停止上一媒体项 换台 双流 适配视频内容帧率 场率 帧率 刷新率 黑屏 闪烁 SurfaceView 兜底刷新率 系统默认 50Hz 59.94Hz 60Hz PAL NTSC 中国 英国 德国 法国 澳大利亚 美国 日本 韩国 加拿大 互联网视频流 更好的视频探测 起播时间 AUD IDR TS HLS无块准备 探测大小 分析时长 环路过滤 精确跳转 android-opaque 记忆播放器和解码配置 Host URL LRU 内核 渲染 软解 清空记忆',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '缓冲与超时',
    keywords: '加载超时 1 2 3 4 5 10 15 20 25 30 45 60秒 超时换源 断线重连 弱网 误判 播放缓冲 0 帧 Media3 VLC 秒 IJK 帧 30帧 双单位 SeekTo方式 重载URL跳转 startAt 播放器seekTo跳转 已缓冲 RTSP传输方式 TCP UDP 稳定 丢包 延迟',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '显示模式',
    keywords: '全局显示模式 原始 填充 裁剪 4:3 16:9 默认16:9 2.35:1 比例 拉伸 铺满 等比裁剪',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '请求与网络',
    keywords: '在链接中提取Header url|Header1=v1&Header2=v2 分隔 Referer Origin 全局UA Mytv.Android 只读 自定义headers Name: Value 错误图标 自定义DNS 仅Media3 HTTP代理 代理规则 正则 URL 共N条规则',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '音量',
    keywords: '音量平衡 Media3 关闭 低 中 高 默认关闭 推荐中 统一均衡 输出音量 动态范围 人声稳定 压平音量波动 仅Media3',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '字幕样式（设置 → 界面 → 字幕设置）',
    keywords: '字幕样式 设置界面 实时预览 示例字幕 使用系统样式 Android无障碍 跟随源嵌入样式 MKV内嵌 字体颜色 12色板 红品红绿蓝青黄黑深灰灰浅灰白透明 背景颜色 边框颜色 描边OUTLINE 窗口颜色 字体大小 10 20 30 180 步进10 dp 背景透明度 0-100% 字幕位置 0-50% 距底部',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: 'ASR 实时字幕（Beta）',
    keywords: 'ASR 实时字幕 Sherpa-ONNX Media3 IJK 启用 下载Sherpa引擎 下载中 解压中 加载中 失败 实验性领先字幕 HLS 标准渲染器 主动解码未来分片 自动回退 领先字幕提前量 0-10000ms 步进100 非领先路径优先流式模型 降低字幕延迟 不会自动下载 VAD类型 Silero TenVad 中英混杂 低信噪比 语音活动检测 断句静音阈值 100-2000ms 步进50 灵敏 连贯 识别模型 分类 云端 中文 英文 多语言 其他语言 名称 语言 大小 描述 状态 未下载 下载中 带百分比 解压中 已开启 点击选择 长按删除 流式 离线 GitHub代理 tar.bz2 Gemini Live Translate 云端 Gemini API Key Google AI Studio 仅存本机 不参与云同步 Gemini端点 官方默认端点',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: 'ASR 实时翻译（Beta）',
    keywords: 'ASR实时翻译 翻译引擎 未配置 腾讯翻译 百度翻译 MTranServer 自托管 腾讯SecretId SecretKey 百度APIKey 密钥 服务器地址 http://192.168.1.100:8989 API Token 无认证 目标语言 en zh ja ko fr de es ru pt it th vi id ms ar yue粤语 默认en 已配置 未配置 TV只读',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '10591 面板（/player）的全部可配置项',
    keywords: '面板播放器 视频播放器内核 渲染方式 记忆配置 强制软解 适配帧率 更好探测 提取Header 全局显示模式 SeekTo 加载超时 毫秒 10000 播放缓冲 秒帧 0 RTSP 音量平衡 正则解码配置 代理规则 ASR凭据 识别模型 占位 /storage/emulated/0 暂未实现 领先字幕提前量 断句静音阈值 翻译引擎按钮组 目标语言文本框 腾讯SecretId密码框 百度APIKey MTranServer服务器地址 全局UA 自定义headers Name:Value 自定义DNS HTTP代理 保存按钮',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '解码器信息',
    keywords: '解码器信息 硬解器 软硬解 最大并发实例 颜色格式 音频码率 视频码率 视频帧率 360P 480P 720P 1080P 2K 4K 8K',
  },
  {
    path: '/player-settings',
    title: '播放器与字幕设置',
    anchor: '',
    section: '与其他功能的联动',
    keywords: '播放器联动 WebView EPG回看 订阅源 http-user-agent http-referrer EXTVLCOPT',
  },
  {
    path: '/settings',
    title: '设置项总览',
    anchor: '#s1',
    section: '§1 通用',
    keywords: '通用设置 SettingsAppScreen SettingsCategoriesScreen SettingsCategories APP 语言 SettingLanguageScreen zh-Hans en ar 中文 English عربي 重启应用 开机自启 appBootLaunch RECEIVE_BOOT_COMPLETED 启动页面 SettingStartupScreen Screens.Dashboard Screens.Live Screens.EpgGuide Screens.Channels Screens.Favorites Screens.Search Screens.MultiView 首页 直播 节目单 全部频道 收藏 搜索 多屏同播 画中画 appPipEnable 互斥 后台播放 appBackgroundPlayEnable 听电视 通知渠道 清除缓存 AppCacheCleaner.clearAllCaches iptvChannelLinePlayableHostList iptvChannelLinePlayableUrlList 恢复初始化 SP.clear SharedPreferences 面板 GeneralComponent',
  },
  {
    path: '/settings',
    title: '设置项总览',
    anchor: '#s5',
    section: '§5 主题',
    keywords: '主题设置 SettingsThemeScreen app_themes.json 颜色模式 themeMode 0浅色 1深色 2跟随系统 分段按钮 配色方案 themeColorProvider 0内置颜色 1基于背景颜色 2朴素颜色 主题包 themeAppCurrent AppThemeDef 分组 http file data:image #纯色 base64 提取主题色 timestamp占位 恢复默认 面板 ThemeComponent 自定义主题 名称 背景 贴图 贴图透明度 mat-slider 0-1 0.01',
  },
  {
    path: '/settings',
    title: '设置项总览',
    anchor: '#s9',
    section: '§9 更新',
    keywords: '更新设置 SettingsUpdateScreen 更新通道 updateChannel stable beta dev SettingsUpdateChannelScreen 稳定版本 预览版本 开发版本 Gitee mytvstable mytvbeta mytvdev 选择后立即检查更新 更新强提醒 updateForceRemind 全屏提醒 消息提示 面板 UpdateComponent mat-button-toggle-group',
  },
  {
    path: '/settings',
    title: '设置项总览',
    anchor: '#s10',
    section: '§10 网络',
    keywords: '网络设置 SettingsNetworkScreen HTTP请求重试次数 networkRetryCount Constants.NETWORK_RETRY_COUNT 10 SettingsNetworkRetryCountScreen 1 2 3 4 5 6 7 8 9 10 15 20 30 40 50 HTTP请求重试间隔时间 networkRetryInterval Constants.NETWORK_RETRY_INTERVAL 1000ms SettingsNetworkRetryIntervalScreen humanizeMs 0 1000 2000 3000 5000 10000 15000 20000 30000 0秒 1秒 2秒 3秒 5秒 10秒 15秒 20秒 30秒 面板 NetworkComponent type=number ms 订阅源 节目单 UA 代理 DNS remoteConfig',
  },
  {
    path: '/settings',
    title: '设置项总览',
    anchor: '#s12',
    section: '§12 权限',
    keywords: '权限 SettingsPermissionsScreen 安装未知应用 REQUEST_INSTALL_PACKAGES rememberCanRequestPackageInstallsPermission 读取外部存储 管理全部文件 READ_EXTERNAL_STORAGE MANAGE_EXTERNAL_STORAGE rememberReadExternalStoragePermission 已授权对勾 未授权叉号 INTERNET RECEIVE_BOOT_COMPLETED WAKE_LOCK ACCESS_WIFI_STATE ACCESS_NETWORK_STATE GET_TASKS READ_PHONE_STATE FOREGROUND_SERVICE FOREGROUND_SERVICE_DATA_SYNC FOREGROUND_SERVICE_MEDIA_PLAYBACK POST_NOTIFICATIONS 夏杰语音 WRITE_EPG_DATA',
  },
  {
    path: '/settings',
    title: '设置项总览',
    anchor: '#s13',
    section: '§13 调试',
    keywords: '调试设置 SettingsDebugScreen 显示性能信息 debugShowFps FPS 帧时间 Jank PSS内存 显示播放器信息 debugShowVideoPlayerMetadata 编码 解码器 采样率 显示布局网格 debugShowLayoutGrids 解码器信息 SettingsDecoderInfoScreen 导出Logcat DebugComponent logcat_时间戳.txt ISO格式 开发者模式 debugDeveloperMode POST /api/configs /ku9/js',
  },
  {
    path: '/settings',
    title: '设置项总览',
    anchor: '#s14',
    section: '§14 日志',
    keywords: '日志 SettingsLogScreen 每秒刷新 delay(1000) Logger.history LOG_HISTORY_MAX_SIZE 100 级别图标 DEBUG BugReport INFO Info WARN Warning ERROR Error tag message cause HH:mm:ss 跨进程 history_pid.jsonl 合并去重 面板 LogComponent 级别筛选 ALL INFO ERROR WARN DEBUG 刷新按钮 日志表格 时间 级别 标签 消息 原因 列宽拖拽 分页 10 20 50 100 /api/logs /api/logcat 10000行',
  },
  {
    path: '/settings',
    title: '设置项总览',
    anchor: '',
    section: '分类速查',
    keywords: '设置分类 SettingsCategories 14大类 APP IPTV EPG UI THEME CONTROL VIDEO_PLAYER WEBVIEW_PLAYER UPDATE NETWORK CLOUD_SYNC PERMISSIONS DEBUG LOG 通用 订阅源 节目单 界面 主题 控制 播放器 WebView 更新 网络 云同步 权限 调试 日志',
  },
  {
    path: '/sync',
    title: '云同步与备份',
    anchor: '',
    section: '五种同步后端',
    keywords: '同步后端 CloudSyncProvider GITHUB_GIST GITEE_GIST NETWORK_URL LOCAL_FILE WEBDAV 枚举值 支持拉取 支持推送 push返回false GitHub Gist Gitee 代码片段 网络链接 只读 本地文件 WebDAV 拉取 推送',
  },
  {
    path: '/sync',
    title: '云同步与备份',
    anchor: '',
    section: '同步哪些数据',
    keywords: '同步数据 CloudSyncData getData version syncAt syncFrom description configs toPartial desensitized 剔除 云同步账号 globalVideoPlayerCore webViewCore replaceSystemWebView iptvChannelHistoryList iptvSourceCurrentIdx iptvChannelLastPlay iptvChannelLinePlayableHostList iptvChannelLinePlayableUrlList uiFocusOptimize ASR翻译设备本地 extraLocalIptvSourceList sourceType==1 fileDir 并行读取 extraChannelNameAlias aliasFile apply fromPartial',
  },
  {
    path: '/sync',
    title: '云同步与备份',
    anchor: '',
    section: 'TV 应用内设置项（设置 → 云同步）',
    keywords: '云同步设置 SettingsCloudSyncScreen 拉取云端 CloudSync.pull 推送云端 CloudSync.push 推送成功自动拉取 云端数据 自动拉取 yyyy-MM-dd HH:mm:ss 长按 apply 无云端数据 cloudSyncAutoPull 系统备份 appBackupEnable MyTVBackupAgent 键值对备份 自动备份 onBackup onFullBackup onRestore 云同步服务商 SettingsCloudSyncProviderScreen 6列网格 支持拉取 不支持拉取 remoteConfig 只读 cloudSyncGithubGistId cloudSyncGithubGistToken cloudSyncGiteeGistId cloudSyncGiteeGistToken cloudSyncNetworkUrl cloudSyncLocalFilePath DEFAULT_LOCAL_SYNC_FILE_PATH cloudSyncWebDavUrl cloudSyncWebDavUsername cloudSyncWebDavPassword',
  },
  {
    path: '/sync',
    title: '云同步与备份',
    anchor: '',
    section: '10591 面板（/sync）的全部可配置项',
    keywords: '面板云同步 BackupComponent mat-button-toggle-group mat-slide-toggle 自动拉取 服务商 GitHub Gist Gitee 网络链接 本地文件 WebDAV ID Token URL 用户名 密码 占位符 example.com webdav.example.com remote.php 推送 configsService.updateData 导入应用数据 AppApi.pushCloudSyncData POST /api/cloud-sync/data 导出应用数据 AppApi.getCloudSyncData syncFrom version syncAt.json',
  },
  {
    path: '/sync',
    title: '云同步与备份',
    anchor: '',
    section: '各后端配置步骤',
    keywords: '配置步骤 GitHub Gist token gist权限 GithubGistSyncRepository api.github.com/gists PATCH Bearer X-GitHub-Api-Version all_configs.json Base64 truncated raw_url Gitee 令牌 gists权限 GiteeGistSyncRepository gitee.com/api/v5/gists access_token WebDavSyncRepository HTTP Basic Credentials.basic PUT GET 坚果云 应用密码 Nextcloud all_configs.json NetworkUrlSyncRepository push返回false URL.readText 网络链接 sync.json LocalFileSyncRepository 末段含. 完整文件名 目录 all_configs.json U盘',
  },
  {
    path: '/sync',
    title: '云同步与备份',
    anchor: '',
    section: '导入 / 导出应用数据',
    keywords: '导入导出 AppApi.getCloudSyncData AppApi.pushCloudSyncData 导出JSON 导入JSON accept=.json 文件名 迁移 换机 不依赖云端',
  },
  {
    path: '/faq',
    title: '常见问题',
    anchor: '',
    section: '常见故障排查',
    keywords: 'FAQ 常见问题 故障 排查 黑屏 无法播放 加载失败 EPG不显示 换台卡顿 缓存',
  },
  {
    path: '/build',
    title: '下载与更新',
    anchor: '',
    section: '下载',
    keywords: '下载 Release APK GitHub Gitee 版本 签名',
  },
  {
    path: '/build',
    title: '下载与更新',
    anchor: '',
    section: '应用内更新',
    keywords: '应用内更新 更新通道 stable beta dev 强提醒',
  },
  {
    path: '/build',
    title: '下载与更新',
    anchor: '',
    section: '自行编译',
    keywords: '自行编译 源码 编译 gradle 签名 ABI',
  },
];
